apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    name: activemq
spec:
  type: NodePort
  ports:
  - port: 8161
    name: http
  - port: 61616
    name: tcp
  - port: 61613
    name: stomp
  selector:
    name: activemq